---
- name: Centos 9+/Redhat 9+ Linux patch management
  hosts: centos9
  become: yes
  tasks:
- name: Upgrade all packages on CentOS Stream 9+/RHEL 9+ (dnf)
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_cache: yes
        autoremove: yes
      when:
        - ansible_facts['os_family'] == "RedHat"
        - ansible_facts['distribution_major_version'] is defined
        - ansible_facts['distribution_major_version'] | int >= 9
