---
- name: Centos 9+/Redhat 9+ Linux patch management
  hosts: all
  become: yes
  tasks:
  ansible.builtin.dnf:
        name: "*"
        state: latest
        update_cache: yes
        autoremove: yes
      when:
        - ansible_facts['os_family'] == "RedHat"
        - ansible_facts['distribution_major_version'] is defined
        - ansible_facts['distribution_major_version'] | int >= 9
- name: Reboot if required (CentOS/RHEL)
  ansible.builtin.reboot:
      reboot_timeout: 600
  when: ansible_facts['os_family'] == "RedHat"
